- name: Deploy to Firebase
  env:
    GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json
  run: |
    echo '${{ secrets.FIREBASE_SA_PROD }}' > service-account.json
    firebase deploy --project cleanup-manager-d9301
